from __future__ import annotations


def _term(
    slug: str,
    term: str,
    term_en: str,
    category: str,
    subcategory: str,
    difficulty: str,
    definition: str,
    interpretation: str,
    tags: list[str],
    source_url: str,
) -> dict:
    """Build one reviewed definition without synthetic metrics or copied source prose."""

    return {
        "slug": slug,
        "term": term,
        "term_en": term_en,
        "category": category,
        "subcategory": subcategory,
        "difficulty": difficulty,
        "definition": definition,
        "formula": "",
        "interpretation": interpretation,
        "tags": tags,
        "source_url": source_url,
    }


AI_GLOSSARY_TERMS = (
    _term(
        "attention",
        "注意力机制",
        "Attention",
        "AI 模型",
        "模型架构",
        "中级",
        "让模型按当前输入与其它位置的相关程度分配权重，再聚合对应信息的计算机制。",
        "注意力权重反映一次计算中的信息路由，不应直接当作因果解释或可靠性证明。",
        ["Transformer", "self-attention", "QKV"],
        "https://research.google/pubs/attention-is-all-you-need/",
    ),
    _term(
        "benchmark",
        "基准测试",
        "Benchmark",
        "AI 模型",
        "评测",
        "入门",
        "用固定任务、数据、指标和运行规则测量模型或系统表现的可重复评测方案。",
        "只有任务、版本、提示、硬件和计分规则一致时，分数才适合直接比较。",
        ["evaluation", "MLPerf", "reproducibility"],
        "https://mlcommons.org/benchmarks/",
    ),
    _term(
        "chiplet",
        "芯粒",
        "Chiplet",
        "半导体设计",
        "先进封装",
        "中级",
        "把处理、存储或接口等功能做成独立裸片，再通过封装内互连组合为完整系统的设计单元。",
        "芯粒化可改善复用与良率，但收益取决于互连标准、封装、功耗、测试和软件协同。",
        ["UCIe", "die-to-die", "heterogeneous integration"],
        "https://www.uciexpress.org/specifications",
    ),
    _term(
        "cowos",
        "CoWoS 先进封装",
        "Chip-on-Wafer-on-Substrate (CoWoS)",
        "AI 基础设施",
        "先进封装",
        "中级",
        "台积电把逻辑裸片、HBM 等器件经中介层整合后再装到封装基板上的专有封装家族。",
        "CoWoS 是品牌化工艺家族；不同 S、R、L 方案的中介层和布线结构不能混为一种规格。",
        ["TSMC", "interposer", "HBM"],
        "https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm",
    ),
    _term(
        "cpo",
        "共封装光学",
        "Co-Packaged Optics (CPO)",
        "AI 基础设施",
        "光互连",
        "高级",
        "把光引擎与交换或计算芯片近距离集成在同一基板或封装中的光电协同方案。",
        "缩短高速电连接有望降低功耗，但可维护性、热管理和互操作性仍是系统约束。",
        ["silicon photonics", "optical engine", "switch ASIC"],
        "https://eps.ieee.org/publications/enews/105-publications/enews/august-2023.html",
    ),
    _term(
        "dram",
        "动态随机存取存储器",
        "Dynamic Random-Access Memory (DRAM)",
        "AI 基础设施",
        "存储器",
        "入门",
        "以需要周期刷新电荷状态的存储单元保存数据、断电后内容消失的易失性主存技术。",
        "DDR、GDDR 与 HBM 都基于 DRAM，但接口、封装和目标带宽不同。",
        ["memory", "DDR", "volatile"],
        "https://www.micron.com/products/memory/dram-components/ddr5-sdram",
    ),
    _term(
        "eda",
        "电子设计自动化",
        "Electronic Design Automation (EDA)",
        "半导体设计",
        "设计工具",
        "入门",
        "辅助集成电路规划、仿真、综合、验证、物理实现和制造准备的软件与硬件工具集合。",
        "EDA 不是单一软件；不同流程阶段需要相互衔接的模型、规则库和签核工具。",
        ["IC design", "verification", "signoff"],
        "https://www.synopsys.com/glossary/what-is-electronic-design-automation.html",
    ),
    _term(
        "embedding",
        "嵌入向量",
        "Embedding",
        "AI 模型",
        "表示学习",
        "入门",
        "把文本、图像或其它对象映射为数值向量，以便计算相似性或交给下游算法处理。",
        "向量接近通常表示模型空间中的相似，不等于事实一致、语义等价或因果关联。",
        ["vector", "semantic search", "representation"],
        "https://openai.com/index/introducing-text-and-code-embeddings/",
    ),
    _term(
        "etch",
        "刻蚀",
        "Etch",
        "晶圆制造",
        "前道工艺",
        "入门",
        "按图形选择性移除晶圆表面薄膜或材料，以形成晶体管、互连和通孔结构的制造步骤。",
        "湿法、等离子体和原子层刻蚀的方向性、选择比与精度不同。",
        ["RIE", "ALE", "wafer fabrication"],
        "https://www.lamresearch.com/products/our-processes/etch/",
    ),
    _term(
        "foundry",
        "晶圆代工",
        "Semiconductor Foundry",
        "晶圆制造",
        "商业模式",
        "入门",
        "依据客户提供的芯片设计和工艺要求制造晶圆，并提供相应工艺平台与设计生态的业务。",
        "纯晶圆代工强调不以自有品牌芯片与客户竞争；它与同时设计制造产品的 IDM 不同。",
        ["fab", "pure-play", "wafer manufacturing"],
        "https://investor.tsmc.com/static/annualReports/2025/english/index.html",
    ),
    _term(
        "gpu-rental",
        "GPU 云租用",
        "GPU Rental",
        "AI 基础设施",
        "云计算",
        "入门",
        "通过云服务按需取得装有 GPU 的虚拟机、裸金属或预留算力，而非自行购置设备。",
        "比较成本时要同时核对 GPU 型号、显存、互连、地域、可用性和计费承诺。",
        ["cloud GPU", "on-demand", "capacity"],
        "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configure-gpu-instances.html",
    ),
    _term(
        "guardrails",
        "AI 防护栏",
        "AI Guardrails",
        "AI 模型",
        "风险管理",
        "中级",
        "围绕模型输入、生成过程、输出和工具执行设置的策略检查、权限限制与监测控制。",
        "防护栏是持续风险管理的一部分，不能保证系统绝对安全，也不能替代人工治理。",
        ["AI RMF", "safety", "policy controls"],
        "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10",
    ),
    _term(
        "hbm",
        "高带宽存储器",
        "High Bandwidth Memory (HBM)",
        "AI 基础设施",
        "存储器",
        "中级",
        "把多层 DRAM 裸片垂直堆叠并以硅通孔连接，通过宽接口靠近处理器部署的存储技术。",
        "HBM 的容量、带宽、堆叠高度和代际需分别核对，不能只用名称推断系统性能。",
        ["DRAM", "TSV", "memory bandwidth"],
        "https://www.micron.com/products/memory/hbm",
    ),
    _term(
        "idm",
        "集成器件制造商",
        "Integrated Device Manufacturer (IDM)",
        "晶圆制造",
        "商业模式",
        "入门",
        "在同一企业体系内承担芯片设计并运营制造能力、销售自有半导体产品的公司模式。",
        "IDM 也可能外包部分制造或提供代工服务，因此应按具体产品和产能判断边界。",
        ["design", "manufacturing", "semiconductor company"],
        "https://download.intel.com/newsroom/archive/2025/en-us-2021-06-09-intels-idm-20-strategy-defined-in-60-seconds.pdf",
    ),
    _term(
        "ip-core",
        "芯片 IP 核",
        "Semiconductor IP Core",
        "半导体设计",
        "设计复用",
        "中级",
        "可授权并复用的预设计功能模块，例如处理器、存储控制器或标准接口实现。",
        "软核、硬核和可配置 IP 的交付形态、可移植性及验证责任不同。",
        ["silicon IP", "reusable block", "interface"],
        "https://www.synopsys.com/glossary/what-is-electronic-design-automation.html",
    ),
    _term(
        "kv-cache",
        "键值缓存",
        "Key-Value Cache (KV Cache)",
        "AI 模型",
        "推理优化",
        "中级",
        "自回归生成时保存已处理 token 在注意力层中的 key 与 value 状态，避免逐步重复计算。",
        "它能减少计算，但会随序列、批量和层数占用显存；量化与复用可能改变质量或隔离要求。",
        ["inference", "attention", "memory"],
        "https://docs.nvidia.com/dynamo/dev/user-guides/multimodal/embedding-cache",
    ),
    _term(
        "lithography",
        "光刻",
        "Photolithography",
        "晶圆制造",
        "前道工艺",
        "入门",
        "利用光学系统把掩模图形缩小并投射到涂有感光材料的晶圆上的图形化工艺。",
        "分辨率不只由光源波长决定，还受数值孔径、工艺因子和多重图形化影响。",
        ["EUV", "DUV", "patterning"],
        "https://www.asml.com/en/technology/lithography-principles",
    ),
    _term(
        "model-api",
        "模型 API",
        "Model API",
        "AI 模型",
        "服务接口",
        "入门",
        "通过网络请求提交输入、选择模型和参数，并接收生成结果或结构化响应的程序接口。",
        "同名模型的版本、区域、速率限制、数据政策和价格可能变化，调用方应固定并记录口径。",
        ["API", "endpoint", "inference service"],
        "https://platform.openai.com/docs/api-reference/introduction",
    ),
    _term(
        "moe",
        "混合专家模型",
        "Mixture of Experts (MoE)",
        "AI 模型",
        "模型架构",
        "高级",
        "由多个专家网络和路由器组成、通常只为每个 token 激活部分专家的稀疏模型架构。",
        "总参数量与单次激活参数量不同；通信、负载均衡和显存仍会限制实际效率。",
        ["sparse model", "router", "experts"],
        "https://pytorch.org/blog/training-moes/",
    ),
    _term(
        "mosfet",
        "金属氧化物半导体场效应晶体管",
        "Metal-Oxide-Semiconductor Field-Effect Transistor (MOSFET)",
        "半导体设计",
        "器件基础",
        "中级",
        "通过绝缘栅极产生的电场控制源极与漏极间导电通道的场效应晶体管。",
        "数字逻辑与功率器件都使用 MOSFET，但结构、工作区和关键损耗指标差异很大。",
        ["transistor", "gate", "CMOS"],
        "https://www.onsemi.com/pub/Collateral/AN-9010.pdf",
    ),
    _term(
        "optical-module",
        "光模块",
        "Optical Transceiver Module",
        "AI 基础设施",
        "光互连",
        "入门",
        "在网络设备电接口与光纤链路之间完成电光和光电转换的可插拔或固定收发组件。",
        "速率、波长、光纤类型、距离、封装和协议必须匹配，标称带宽不能单独代表链路能力。",
        ["transceiver", "QSFP", "data center network"],
        "https://www.cisco.com/c/en/us/td/docs/interfaces_modules/transceiver_modules/installation/note/OL_24862.html",
    ),
    _term(
        "parameter",
        "模型参数",
        "Model Parameter",
        "AI 模型",
        "训练基础",
        "入门",
        "训练过程中由数据与优化算法调整、用于决定模型变换结果的权重或偏置等数值。",
        "参数量描述容量规模之一，不等同于有效计算量、数据质量或任务能力。",
        ["weights", "bias", "training"],
        "https://developers.google.com/machine-learning/glossary/#parameter",
    ),
    _term(
        "photoresist",
        "光刻胶",
        "Photoresist",
        "晶圆制造",
        "光刻材料",
        "入门",
        "涂覆在晶圆上并因曝光而改变溶解性质，用于把光刻图形转移到后续工艺的感光材料。",
        "正胶与负胶的曝光响应相反，配方需与光源、显影和目标图形共同优化。",
        ["resist", "exposure", "pattern transfer"],
        "https://www.asml.com/en/news/stories/2021/semiconductor-manufacturing-process-steps",
    ),
    _term(
        "pn-junction",
        "PN 结",
        "P-N Junction",
        "半导体设计",
        "器件基础",
        "中级",
        "P 型与 N 型半导体接触后形成耗尽区和内建电场的基础器件结构。",
        "外加偏压会改变势垒与载流子流动，具体行为还取决于材料、掺杂和器件结构。",
        ["semiconductor", "diode", "depletion region"],
        "https://www.onsemi.com/pub/Collateral/AN-9010.pdf",
    ),
    _term(
        "pretraining",
        "预训练",
        "Pre-training",
        "AI 模型",
        "训练基础",
        "入门",
        "先在大规模通用数据上训练模型以获得基础表示与能力，再进入微调或对齐阶段的过程。",
        "预训练数据、目标函数和计算预算会影响能力与风险，不能只看数据量判断质量。",
        ["foundation model", "training", "base model"],
        "https://developers.google.com/machine-learning/glossary/#pre-training",
    ),
    _term(
        "quantization",
        "模型量化",
        "Model Quantization",
        "AI 模型",
        "推理优化",
        "中级",
        "用更低精度的数值格式表示权重、激活或缓存，以降低内存占用并加速计算的技术。",
        "实际收益取决于硬件和算子支持；精度选择与校准也可能造成任务质量损失。",
        ["INT8", "FP8", "PTQ"],
        "https://docs.nvidia.com/nemotron/latest/nemotron/super3/quantization.html",
    ),
    _term(
        "rag",
        "检索增强生成",
        "Retrieval-Augmented Generation (RAG)",
        "AI 模型",
        "知识系统",
        "中级",
        "在生成前检索外部文档或记录，并把相关内容作为上下文交给生成模型的系统方法。",
        "检索来源可更新且可追溯，但最终答案仍受召回、排序、上下文和生成错误影响。",
        ["retrieval", "generation", "provenance"],
        "https://ai.meta.com/research/publications/retrieval-augmented-generation-for-knowledge-intensive-nlp-tasks/",
    ),
    _term(
        "rlhf",
        "基于人类反馈的强化学习",
        "Reinforcement Learning from Human Feedback (RLHF)",
        "AI 模型",
        "模型对齐",
        "中级",
        "把人类对模型输出的示范或偏好转化为训练信号，用强化学习调整模型行为的方法。",
        "结果依赖反馈人群、标注规范与优化流程，偏好提升不等于事实性或安全性得到保证。",
        ["alignment", "preference data", "reinforcement learning"],
        "https://openai.com/index/instruction-following/",
    ),
    _term(
        "silicon-wafer",
        "硅晶圆",
        "Silicon Wafer",
        "晶圆制造",
        "基础材料",
        "入门",
        "由高纯单晶硅锭切片、研磨和抛光形成，供半导体器件逐层制造的圆形基底。",
        "直径、晶向、掺杂、电阻率、平坦度和缺陷水平会影响适用工艺与良率。",
        ["substrate", "single crystal", "wafer fabrication"],
        "https://www.sumcosi.com/english/products/process/",
    ),
    _term(
        "token",
        "词元",
        "Token",
        "AI 模型",
        "文本处理",
        "入门",
        "分词器把输入拆成、模型据以处理和计费的文本单元，可能是字符、子词、标点或整词。",
        "不同模型和语言的分词规则不同，字符数、词数与 token 数不能固定换算。",
        ["tokenizer", "context", "billing"],
        "https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them",
    ),
    _term(
        "tool-calling",
        "工具调用",
        "Tool Calling",
        "AI 模型",
        "智能体系统",
        "中级",
        "模型按开发者提供的工具定义生成结构化参数，由宿主程序校验、执行并把结果返回模型的机制。",
        "模型提出调用不等于动作已执行；权限、参数校验、幂等性和审计由应用负责。",
        ["function calling", "agents", "JSON Schema"],
        "https://openai.com/index/function-calling-and-other-api-updates/",
    ),
    _term(
        "vlm",
        "视觉语言模型",
        "Vision-Language Model (VLM)",
        "AI 模型",
        "多模态",
        "中级",
        "联合处理图像或视频与文本，使模型能围绕视觉内容理解、检索或生成语言的多模态模型。",
        "不同 VLM 的输入分辨率、视频采样、文字识别与空间推理能力不能由名称一概而论。",
        ["multimodal", "vision", "language"],
        "https://research.google/pubs/simvlm-simple-visual-language-model-pretaining-with-weak-supervision/",
    ),
)

AI_GLOSSARY_TERM_SLUGS = tuple(item["slug"] for item in AI_GLOSSARY_TERMS)

assert len(AI_GLOSSARY_TERM_SLUGS) == 32
assert len(set(AI_GLOSSARY_TERM_SLUGS)) == len(AI_GLOSSARY_TERM_SLUGS)
