"""Reviewed public GitHub project seed list for the applications radar."""

GITHUB_PROJECT_SEEDS = [
    ("langchain-ai/langchain", "Agent / orchestration"),
    ("run-llama/llama_index", "Agent / orchestration"),
    ("microsoft/autogen", "Agent / orchestration"),
    ("crewAIInc/crewAI", "Agent / orchestration"),
    ("openai/openai-agents-python", "Agent / orchestration"),
    ("microsoft/semantic-kernel", "Agent / orchestration"),
    ("browser-use/browser-use", "Agent / orchestration"),
    ("modelcontextprotocol/python-sdk", "Agent / orchestration"),
    ("modelcontextprotocol/servers", "Agent / orchestration"),
    ("mem0ai/mem0", "Agent memory"),
    ("langgenius/dify", "AI applications"),
    ("FlowiseAI/Flowise", "AI applications"),
    ("open-webui/open-webui", "AI applications"),
    ("khoj-ai/khoj", "AI applications"),
    ("QuivrHQ/quivr", "AI applications"),
    ("n8n-io/n8n", "AI applications"),
    ("ollama/ollama", "Inference"),
    ("vllm-project/vllm", "Inference"),
    ("ggml-org/llama.cpp", "Inference"),
    ("huggingface/text-generation-inference", "Inference"),
    ("BerriAI/litellm", "Inference"),
    ("lm-sys/FastChat", "Inference"),
    ("ml-explore/mlx", "Inference"),
    ("exo-explore/exo", "Inference"),
    ("OpenHands/OpenHands", "Coding agent"),
    ("aider-ai/aider", "Coding agent"),
    ("continuedev/continue", "Coding agent"),
    ("cline/cline", "Coding agent"),
    ("RooCodeInc/Roo-Code", "Coding agent"),
    ("TabbyML/tabby", "Coding agent"),
    ("aaif-goose/goose", "Coding agent"),
    ("deepset-ai/haystack", "RAG / vector data"),
    ("qdrant/qdrant", "RAG / vector data"),
    ("milvus-io/milvus", "RAG / vector data"),
    ("weaviate/weaviate", "RAG / vector data"),
    ("chroma-core/chroma", "RAG / vector data"),
    ("zilliztech/GPTCache", "RAG / vector data"),
    ("huggingface/transformers", "Model tooling"),
    ("huggingface/diffusers", "Multimodal"),
    ("Comfy-Org/ComfyUI", "Multimodal"),
    ("AUTOMATIC1111/stable-diffusion-webui", "Multimodal"),
    ("invoke-ai/InvokeAI", "Multimodal"),
    ("ultralytics/ultralytics", "Computer vision"),
    ("PaddlePaddle/PaddleOCR", "Computer vision"),
    ("roboflow/supervision", "Computer vision"),
]
