# Generated by Django 5.2.16 on 2026-07-11 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=800)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='research.generatedanalysis')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.observation')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.metricsnapshot')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='research.source')),
                ('thesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='research.thesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.CharField(db_index=True, max_length=160)),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('reason', models.TextField()),
                ('began_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('fallback_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activated_fallback_events', to='research.source')),
                ('primary_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_fallback_events', to='research.source')),
            ],
            options={
                'ordering': ['-began_at'],
            },
        ),
        migrations.CreateModel(
            name='Invalidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.TextField()),
                ('is_triggered', models.BooleanField(default=False)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invalidation_record', to='research.thesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '待复盘'), ('hit', '命中'), ('partial', '部分命中'), ('missed', '未命中')], max_length=20)),
                ('hit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('simulated_return', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='research.thesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('scope_key', models.CharField(db_index=True, max_length=160)),
                ('check_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pass', '通过'), ('warn', '警告'), ('fail', '失败')], max_length=12)),
                ('observed_at', models.DateTimeField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='research.ingestionrun')),
            ],
            options={
                'ordering': ['-observed_at', 'scope_key'],
            },
        ),
        migrations.CreateModel(
            name='SourceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', '开放'), ('review', '待审核'), ('licensed', '已授权'), ('restricted', '受限制')], default='review', max_length=20)),
                ('scope', models.TextField()),
                ('terms_url', models.URLField(blank=True, max_length=800)),
                ('redistribution_allowed', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='research.source')),
            ],
            options={
                'ordering': ['-reviewed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('condition', models.TextField()),
                ('display_threshold', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('watching', '观察中'), ('triggered', '已触发'), ('expired', '已过期')], default='watching', max_length=20)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_items', to='research.thesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(default='1d', max_length=20)),
                ('value_date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=28)),
                ('high', models.DecimalField(decimal_places=8, max_digits=28)),
                ('low', models.DecimalField(decimal_places=8, max_digits=28)),
                ('close', models.DecimalField(decimal_places=8, max_digits=28)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('quality_status', models.CharField(choices=[('fresh', '正常'), ('stale', '过期'), ('fallback', '备用源'), ('estimated', '估算'), ('error', '异常')], default='fresh', max_length=20)),
                ('license_scope', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fallback_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fallback_market_bars', to='research.source')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='research.instrument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_bars', to='research.source')),
            ],
            options={
                'ordering': ['-value_date'],
                'indexes': [models.Index(fields=['instrument', 'interval', '-value_date'], name='research_ma_instrum_66f1ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'interval', 'value_date', 'source'), name='market_bar_source_interval_time')],
            },
        ),
    ]
