# Generated by Django 5.2.16 on 2026-07-12 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_enable_postgres_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=160, unique=True)),
                ('page_key', models.SlugField(max_length=120)),
                ('metric_name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('live', '已接入'), ('proxy', '代理指标'), ('needs_source', '待找数据源'), ('license_review', '许可待审核'), ('purchase_required', '需采购')], max_length=24)),
                ('source_name', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(blank=True, max_length=800)),
                ('vendor', models.CharField(blank=True, max_length=180)),
                ('product', models.CharField(blank=True, max_length=240)),
                ('reason', models.TextField(blank=True)),
                ('proxy_description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority', 'page_key', 'metric_name'],
            },
        ),
        migrations.AddField(
            model_name='sourcelicense',
            name='ai_use_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcelicense',
            name='derived_display_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcelicense',
            name='historical_storage_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcelicense',
            name='public_display_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcelicense',
            name='territories',
            field=models.CharField(blank=True, help_text='Contracted display territories; blank means not confirmed.', max_length=240),
        ),
        migrations.CreateModel(
            name='CFTCPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(default='tff-futures', max_length=30)),
                ('report_date', models.DateField(db_index=True)),
                ('market_code', models.CharField(db_index=True, max_length=24)),
                ('market_name', models.CharField(max_length=240)),
                ('trader_group', models.CharField(db_index=True, max_length=40)),
                ('long_positions', models.BigIntegerField()),
                ('short_positions', models.BigIntegerField()),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('quality_status', models.CharField(choices=[('fresh', '正常'), ('stale', '过期'), ('fallback', '备用源'), ('estimated', '估算'), ('error', '异常')], default='fresh', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.source')),
            ],
            options={
                'ordering': ['-report_date', 'market_name', 'trader_group'],
                'indexes': [models.Index(fields=['market_code', 'trader_group', '-report_date'], name='research_cf_market__d239c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('report_type', 'report_date', 'market_code', 'trader_group'), name='unique_cftc_position_snapshot')],
            },
        ),
    ]
