# Generated by Django 5.2.16 on 2026-07-12 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_datarequirement_sourcelicense_ai_use_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cusip', models.CharField(max_length=16)),
                ('security_type', models.CharField(max_length=40)),
                ('security_term', models.CharField(max_length=40)),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('auction_date', models.DateField(db_index=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('offering_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('total_tendered', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('total_accepted', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('bid_to_cover_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('high_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('indirect_bidder_accepted', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('direct_bidder_accepted', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('primary_dealer_accepted', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('quality_status', models.CharField(choices=[('fresh', '正常'), ('stale', '过期'), ('fallback', '备用源'), ('estimated', '估算'), ('error', '异常')], default='fresh', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.source')),
            ],
            options={
                'ordering': ['-auction_date', 'security_type', 'security_term'],
                'constraints': [models.UniqueConstraint(fields=('cusip', 'auction_date'), name='unique_treasury_auction')],
            },
        ),
    ]
