# Generated by Django 5.2.16 on 2026-07-12 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_treasuryauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubproject',
            name='data_as_of',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubproject',
            name='quality_status',
            field=models.CharField(choices=[('fresh', '正常'), ('stale', '过期'), ('fallback', '备用源'), ('estimated', '估算'), ('error', '异常')], default='fresh', max_length=20),
        ),
        migrations.AddField(
            model_name='githubproject',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='research.source'),
        ),
        migrations.CreateModel(
            name='GitHubProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='research.githubproject')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.source')),
            ],
            options={
                'ordering': ['-snapshot_date', 'project__repo'],
                'constraints': [models.UniqueConstraint(fields=('project', 'snapshot_date'), name='unique_github_project_daily_snapshot')],
            },
        ),
    ]
