# Generated by Django 5.2.16 on 2026-07-12 03:59

import django.db.models.deletion
from django.db import migrations, models

DEMO_SUMMARY_PREFIX = "演示日报 "


def publish_existing_non_demo_theses(apps, schema_editor):
    """Preserve legitimate reports when publication controls are introduced."""

    Thesis = apps.get_model("research", "Thesis")
    (
        Thesis.objects.filter(is_published=False, published_at__isnull=True)
        .exclude(summary__startswith=DEMO_SUMMARY_PREFIX)
        .update(is_published=True, published_at=models.F("updated_at"))
    )


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0006_githubproject_data_as_of_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="thesis",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thesis",
            name="source_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_theses",
                to="research.dashboardsnapshot",
            ),
        ),
        migrations.RunPython(
            publish_existing_non_demo_theses,
            migrations.RunPython.noop,
        ),
    ]
