# Generated by Django 5.2.16 on 2026-07-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_thesis_is_published_thesis_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubproject',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='githubproject',
            name='is_fork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='githubproject',
            name='license_spdx',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
