# Generated by Django 5.2.16 on 2026-07-12 04:40

from django.db import migrations, models


def keep_latest_license_current(apps, schema_editor):
    SourceLicense = apps.get_model("research", "SourceLicense")
    source_ids = SourceLicense.objects.values_list("source_id", flat=True).distinct()
    for source_id in source_ids.iterator():
        licenses = SourceLicense.objects.filter(source_id=source_id).order_by("-created_at", "-pk")
        latest = licenses.first()
        licenses.update(is_current=False)
        if latest is not None:
            SourceLicense.objects.filter(pk=latest.pk).update(is_current=True)


def restore_all_licenses_current(apps, schema_editor):
    SourceLicense = apps.get_model("research", "SourceLicense")
    SourceLicense.objects.update(is_current=True)


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0008_githubproject_archived_githubproject_is_fork_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sourcelicense",
            options={"ordering": ["-created_at", "-pk"]},
        ),
        migrations.AddField(
            model_name="sourcelicense",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sourcelicense",
            name="required_notice",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(keep_latest_license_current, restore_all_licenses_current),
    ]
