# Generated by Django 5.2.16 on 2026-07-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0010_sourcelicense_current_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="cftcposition",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Initial PRE row publication timestamp from the Socrata :created_at field.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cftcposition",
            name="source_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Latest PRE row revision timestamp from the Socrata :updated_at field.",
                null=True,
            ),
        ),
    ]
