# Generated by Django 5.2.16 on 2026-07-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_cftc_publication_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundletter',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
