# Generated by Django 5.2.16 on 2026-07-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_fundletter_unknown_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingagentprofile',
            name='capability_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='codingagentprofile',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='capability_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
