# Generated by Django 5.2.16 on 2026-07-12 13:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0013_nullable_ai_reference_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseVintageObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.DecimalField(decimal_places=8, max_digits=28)),
                ("value_date", models.DateTimeField()),
                ("as_of", models.DateTimeField()),
                ("release_date", models.DateField()),
                ("estimate_round", models.CharField(max_length=60)),
                ("vintage_label", models.CharField(max_length=120)),
                ("fetched_at", models.DateTimeField()),
                ("batch_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("fresh", "正常"),
                            ("stale", "过期"),
                            ("fallback", "备用源"),
                            ("estimated", "估算"),
                            ("error", "异常"),
                        ],
                        default="fresh",
                        max_length=20,
                    ),
                ),
                ("license_scope", models.CharField(blank=True, max_length=240)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "fallback_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fallback_release_vintage_observations",
                        to="research.source",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_vintages",
                        to="research.seriesdefinition",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_vintage_observations",
                        to="research.source",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-value_date",
                    "release_date",
                    "estimate_round",
                    "series",
                ],
                "indexes": [
                    models.Index(
                        fields=["series", "-value_date", "release_date"],
                        name="research_re_series__389ae3_idx",
                    ),
                    models.Index(
                        fields=["source", "batch_id"],
                        name="research_re_source__e910d7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "series",
                            "value_date",
                            "release_date",
                            "estimate_round",
                            "source",
                        ),
                        name="release_vintage_series_period_round_source",
                    )
                ],
            },
        ),
    ]
