# Generated by Django 5.2.16 on 2026-07-13

from django.db import migrations, models


def unpublish_legacy_theses(apps, schema_editor):
    """Fail closed because legacy rows have no verifiable review contract."""

    Thesis = apps.get_model("research", "Thesis")
    Thesis.objects.all().update(
        is_published=False,
        published_at=None,
        review_status="draft",
        reviewed_by="",
        reviewed_at=None,
        publication_fingerprint="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0014_releasevintageobservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("reviewed", "已审核"),
                    ("rejected", "已拒绝"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="thesis",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thesis",
            name="reviewed_by",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="thesis",
            name="publication_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(unpublish_legacy_theses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="thesis",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(is_published=False, published_at__isnull=True)
                    | (
                        models.Q(
                            is_published=True,
                            published_at__isnull=False,
                            review_status="reviewed",
                            reviewed_at__isnull=False,
                            source_snapshot__isnull=False,
                        )
                        & ~models.Q(reviewed_by="")
                        & ~models.Q(publication_fingerprint="")
                    )
                ),
                name="thesis_publication_review_state_consistent",
            ),
        ),
        migrations.AlterModelOptions(
            name="thesis",
            options={
                "ordering": ["-date"],
                "permissions": [
                    ("publish_thesis", "Can review and publish thesis"),
                    ("withdraw_thesis", "Can withdraw published thesis"),
                ],
            },
        ),
    ]
